[package]
name = "pl-app"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
pl-capture = { path = "../pl-capture" }
pl-core = { path = "../pl-core" }
pl-reassembly = { path = "../pl-reassembly" }
pl-project = { version = "0.1.0", path = "../pl-project" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
sha2 = "0.11.0"
tokio = { version = "1.53.2", features = ["rt", "sync", "macros"] }
tokio-util = "0.7.20"
tracing = "0.1.44"

[dev-dependencies]
tokio = { version = "1.53.2", features = ["rt", "sync", "macros", "time"] }
